/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnsubscribeSuccessRouteImport } from './routes/unsubscribe-success'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UnsubscribeUnsubscribeIdRouteImport } from './routes/unsubscribe.$unsubscribeId'
import { Route as DashboardListRouteImport } from './routes/dashboard.list'
import { Route as DashboardComposeRouteImport } from './routes/dashboard.compose'
import { Route as ApiSubscribeRouteImport } from './routes/api/subscribe'
import { Route as ApiExportRouteImport } from './routes/api/export'
import { Route as ApiBouncedRouteImport } from './routes/api/bounced'
import { Route as DashboardComposeTemplateIdRouteImport } from './routes/dashboard.compose.$templateId'

const UnsubscribeSuccessRoute = UnsubscribeSuccessRouteImport.update({
  id: '/unsubscribe-success',
  path: '/unsubscribe-success',
  getParentRoute: () => rootRouteImport,
} as any)
const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UnsubscribeUnsubscribeIdRoute =
  UnsubscribeUnsubscribeIdRouteImport.update({
    id: '/unsubscribe/$unsubscribeId',
    path: '/unsubscribe/$unsubscribeId',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardListRoute = DashboardListRouteImport.update({
  id: '/list',
  path: '/list',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardComposeRoute = DashboardComposeRouteImport.update({
  id: '/compose',
  path: '/compose',
  getParentRoute: () => DashboardRoute,
} as any)
const ApiSubscribeRoute = ApiSubscribeRouteImport.update({
  id: '/api/subscribe',
  path: '/api/subscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExportRoute = ApiExportRouteImport.update({
  id: '/api/export',
  path: '/api/export',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBouncedRoute = ApiBouncedRouteImport.update({
  id: '/api/bounced',
  path: '/api/bounced',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardComposeTemplateIdRoute =
  DashboardComposeTemplateIdRouteImport.update({
    id: '/$templateId',
    path: '/$templateId',
    getParentRoute: () => DashboardComposeRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/unsubscribe-success': typeof UnsubscribeSuccessRoute
  '/api/bounced': typeof ApiBouncedRoute
  '/api/export': typeof ApiExportRoute
  '/api/subscribe': typeof ApiSubscribeRoute
  '/dashboard/compose': typeof DashboardComposeRouteWithChildren
  '/dashboard/list': typeof DashboardListRoute
  '/unsubscribe/$unsubscribeId': typeof UnsubscribeUnsubscribeIdRoute
  '/dashboard/compose/$templateId': typeof DashboardComposeTemplateIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/unsubscribe-success': typeof UnsubscribeSuccessRoute
  '/api/bounced': typeof ApiBouncedRoute
  '/api/export': typeof ApiExportRoute
  '/api/subscribe': typeof ApiSubscribeRoute
  '/dashboard/compose': typeof DashboardComposeRouteWithChildren
  '/dashboard/list': typeof DashboardListRoute
  '/unsubscribe/$unsubscribeId': typeof UnsubscribeUnsubscribeIdRoute
  '/dashboard/compose/$templateId': typeof DashboardComposeTemplateIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/unsubscribe-success': typeof UnsubscribeSuccessRoute
  '/api/bounced': typeof ApiBouncedRoute
  '/api/export': typeof ApiExportRoute
  '/api/subscribe': typeof ApiSubscribeRoute
  '/dashboard/compose': typeof DashboardComposeRouteWithChildren
  '/dashboard/list': typeof DashboardListRoute
  '/unsubscribe/$unsubscribeId': typeof UnsubscribeUnsubscribeIdRoute
  '/dashboard/compose/$templateId': typeof DashboardComposeTemplateIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/logout'
    | '/unsubscribe-success'
    | '/api/bounced'
    | '/api/export'
    | '/api/subscribe'
    | '/dashboard/compose'
    | '/dashboard/list'
    | '/unsubscribe/$unsubscribeId'
    | '/dashboard/compose/$templateId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/logout'
    | '/unsubscribe-success'
    | '/api/bounced'
    | '/api/export'
    | '/api/subscribe'
    | '/dashboard/compose'
    | '/dashboard/list'
    | '/unsubscribe/$unsubscribeId'
    | '/dashboard/compose/$templateId'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/logout'
    | '/unsubscribe-success'
    | '/api/bounced'
    | '/api/export'
    | '/api/subscribe'
    | '/dashboard/compose'
    | '/dashboard/list'
    | '/unsubscribe/$unsubscribeId'
    | '/dashboard/compose/$templateId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
  LogoutRoute: typeof LogoutRoute
  UnsubscribeSuccessRoute: typeof UnsubscribeSuccessRoute
  ApiBouncedRoute: typeof ApiBouncedRoute
  ApiExportRoute: typeof ApiExportRoute
  ApiSubscribeRoute: typeof ApiSubscribeRoute
  UnsubscribeUnsubscribeIdRoute: typeof UnsubscribeUnsubscribeIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unsubscribe-success': {
      id: '/unsubscribe-success'
      path: '/unsubscribe-success'
      fullPath: '/unsubscribe-success'
      preLoaderRoute: typeof UnsubscribeSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unsubscribe/$unsubscribeId': {
      id: '/unsubscribe/$unsubscribeId'
      path: '/unsubscribe/$unsubscribeId'
      fullPath: '/unsubscribe/$unsubscribeId'
      preLoaderRoute: typeof UnsubscribeUnsubscribeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/list': {
      id: '/dashboard/list'
      path: '/list'
      fullPath: '/dashboard/list'
      preLoaderRoute: typeof DashboardListRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/compose': {
      id: '/dashboard/compose'
      path: '/compose'
      fullPath: '/dashboard/compose'
      preLoaderRoute: typeof DashboardComposeRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/api/subscribe': {
      id: '/api/subscribe'
      path: '/api/subscribe'
      fullPath: '/api/subscribe'
      preLoaderRoute: typeof ApiSubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/export': {
      id: '/api/export'
      path: '/api/export'
      fullPath: '/api/export'
      preLoaderRoute: typeof ApiExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bounced': {
      id: '/api/bounced'
      path: '/api/bounced'
      fullPath: '/api/bounced'
      preLoaderRoute: typeof ApiBouncedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/compose/$templateId': {
      id: '/dashboard/compose/$templateId'
      path: '/$templateId'
      fullPath: '/dashboard/compose/$templateId'
      preLoaderRoute: typeof DashboardComposeTemplateIdRouteImport
      parentRoute: typeof DashboardComposeRoute
    }
  }
}

interface DashboardComposeRouteChildren {
  DashboardComposeTemplateIdRoute: typeof DashboardComposeTemplateIdRoute
}

const DashboardComposeRouteChildren: DashboardComposeRouteChildren = {
  DashboardComposeTemplateIdRoute: DashboardComposeTemplateIdRoute,
}

const DashboardComposeRouteWithChildren =
  DashboardComposeRoute._addFileChildren(DashboardComposeRouteChildren)

interface DashboardRouteChildren {
  DashboardComposeRoute: typeof DashboardComposeRouteWithChildren
  DashboardListRoute: typeof DashboardListRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardComposeRoute: DashboardComposeRouteWithChildren,
  DashboardListRoute: DashboardListRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
  LogoutRoute: LogoutRoute,
  UnsubscribeSuccessRoute: UnsubscribeSuccessRoute,
  ApiBouncedRoute: ApiBouncedRoute,
  ApiExportRoute: ApiExportRoute,
  ApiSubscribeRoute: ApiSubscribeRoute,
  UnsubscribeUnsubscribeIdRoute: UnsubscribeUnsubscribeIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
